"""Guard the supervisor's two invariants: one run at a time, and stop is honest.

Both fail silently rather than loudly. Two overlapping runs still produce
results -- each just measures the other's queueing delay as its own latency. A
stop that does not mark its manifests leaves a killed job reading as "running"
forever, so its partial results look like a benchmark in progress rather than
the baseline they are.

Needs no model server and no Docker: no test here starts a real benchmark.

    python tests/test_supervisor.py
"""

import json
import subprocess
import sys
import tempfile
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from bench.config import Config, EndpointConfig  # noqa: E402
from bench.supervisor import (  # noqa: E402
    MANIFEST_NAME,
    Job,
    Supervisor,
    SupervisorError,
    _kill_tree,
    _process_group_kwargs,
    _terminate_tree,
    delete_run,
)

failures: list[str] = []


def check(label: str, got: object, want: object) -> None:
    ok = got == want
    print(f"{'PASS' if ok else 'FAIL'}  {label:<52} got={got!r} want={want!r}")
    if not ok:
        failures.append(label)


def raises(fn) -> bool:
    try:
        fn()
        return False
    except SupervisorError:
        return True


def test_guards(tmp: Path) -> None:
    config = Config(endpoint=EndpointConfig(), runs_dir=str(tmp))
    sup = Supervisor(config)
    check("idle to begin with", sup.is_active(), False)
    check("stopping nothing is refused", raises(lambda: sup.stop()), True)

    # Pretend a run is in flight without starting one.
    sup._job = type("J", (), {"status": "running"})()
    check("second run refused", raises(lambda: sup.start(harnesses=["a"])), True)
    check("prepull refused too", raises(lambda: sup.start_prepull()), True)
    # Swapping the endpoint mid-run would mislabel everything after the change.
    check(
        "config change refused mid-run",
        raises(lambda: sup.set_config(config)),
        True,
    )
    sup._job = None
    sup.set_config(config)
    check("config change allowed when idle", sup.is_active(), False)


def test_delete_guards(tmp: Path) -> None:
    """run_id arrives from the browser, so it is treated as hostile."""
    runs = tmp / "runs"
    runs.mkdir(exist_ok=True)
    (runs / "good").mkdir()
    (runs / "good" / "f").write_text("x" * 64, encoding="utf-8")

    for bad in ("..", "../..", "a/b", "a\\b", ".hidden", "", "missing"):
        check(f"rejects {bad!r}", raises(lambda b=bad: delete_run(runs, b)), True)

    result = delete_run(runs, "good")
    check("deletes a real run", result["deleted"], "good")
    check("  reports freed bytes", result["freed_bytes"], 64)
    check("  and it is gone", (runs / "good").exists(), False)


def test_stop_marks_manifests(tmp: Path) -> None:
    """A stopped job must be recorded as stopped, not left reading as running.

    bench/collect.py reads exactly these two fields to decide that a run is a
    stopped baseline rather than one still in flight.
    """
    runs = tmp / "marked"
    runs.mkdir()
    config = Config(endpoint=EndpointConfig(), runs_dir=str(runs))
    sup = Supervisor(config)

    # One directory that predates the job, one it created.
    old = runs / "before__m__1"
    old.mkdir()
    (old / MANIFEST_NAME).write_text(json.dumps({"harness": "old"}), encoding="utf-8")

    job = type("J", (), {"_preexisting": {"before__m__1"}})()
    new = runs / "during__m__2"
    new.mkdir()
    (new / MANIFEST_NAME).write_text(json.dumps({"harness": "new"}), encoding="utf-8")

    sup._mark_manifests_stopped(job, "stopped from the dashboard")

    after_new = json.loads((new / MANIFEST_NAME).read_text(encoding="utf-8"))
    after_old = json.loads((old / MANIFEST_NAME).read_text(encoding="utf-8"))
    check("this run's manifest is marked", "stopped_at" in after_new, True)
    check("  with the reason", after_new["stopped_reason"], "stopped from the dashboard")
    check("earlier runs are left alone", "stopped_at" in after_old, False)


def test_child_env_pins_config(tmp: Path) -> None:
    """The child must run against exactly the endpoint the server holds.

    Otherwise a UI edit and the subprocess can disagree, and a run labelled with
    one model but generated by another looks entirely normal in the output.
    """
    config = Config(
        endpoint=EndpointConfig(
            provider="openrouter", base_url="https://example.invalid/api/v1",
            model="a/b", label="Test", api_key="sk-test-key-abcdefghij",
        ),
        runs_dir=str(tmp),
    )
    env = Supervisor(config)._child_endpoint_env()
    check("provider pinned", env["HARNESS_BENCH_PROVIDER"], "openrouter")
    check("base url pinned", env["HARNESS_BENCH_BASE_URL"], "https://example.invalid/api/v1")
    check("model pinned", env["HARNESS_BENCH_MODEL"], "a/b")
    check("label pinned", env["HARNESS_BENCH_LABEL"], "Test")
    # The key travels in the environment; an argv is world-readable.
    check("key passed by env var", env["OPENROUTER_API_KEY"], "sk-test-key-abcdefghij")
    check("  under a named variable", env["HARNESS_BENCH_API_KEY_ENV"], "OPENROUTER_API_KEY")


def test_a_running_benchmarks_containers_are_not_orphans(tmp: Path) -> None:
    """"Orphaned" is not readable from a container's name.

    While a run is in flight the Harbor-shaped containers on the machine are
    that run's own trials. Anything reporting them as leftovers is inviting
    someone to delete a live benchmark -- and this list is what fills the
    maintenance panel sitting next to a Remove button.
    """
    import bench.supervisor as sup

    supervisor = Supervisor(Config(endpoint=EndpointConfig(), runs_dir=str(tmp)))
    running = ["stale__env-main-1", "trial-a__env-main-1", "trial-b__env-main-1"]
    original = sup.harbor_containers
    sup.harbor_containers = lambda: list(running)
    try:
        check("with no run, everything Harbor-shaped is a leftover",
              sorted(supervisor.orphaned_containers()), sorted(running))

        # A run in flight: it owns whatever appeared after it started, which is
        # exactly the rule the reap-on-stop uses.
        job = Job(id="j", argv=[], harnesses=["h"], started_at="now",
                  log_path=tmp / "j.log", status="running")
        job._precontainers = {"stale__env-main-1"}
        supervisor._job = job

        got = supervisor.orphaned_containers()
        check("a live run's own trials are not offered for removal",
              [c for c in got if c.startswith("trial-")], [])
        check("  but a leftover that predates it still is",
              got, ["stale__env-main-1"])

        # Once it finishes, ownership lapses and its containers are fair game.
        job.status = "finished"
        check("after the run ends they are leftovers again",
              sorted(supervisor.orphaned_containers()), sorted(running))
    finally:
        sup.harbor_containers = original


def test_a_cli_run_is_recognised_across_processes(tmp: Path) -> None:
    """A benchmark started from a terminal builds no Supervisor.

    So the dashboard beside it holds no job, and without a marker it would
    report that run's live trials as leftovers -- next to a Remove button. The
    marker carries the containers that predated the run, which is the same line
    a Supervisor draws for its own jobs.
    """
    import bench.supervisor as sup

    runs = tmp / "cli"
    runs.mkdir()
    supervisor = Supervisor(Config(endpoint=EndpointConfig(), runs_dir=str(runs)))
    original = sup.harbor_containers
    try:
        # Written when only the leftover was up; the trials appear afterwards.
        sup.harbor_containers = lambda: ["stale__env-main-1"]
        sup.write_run_marker(runs, ["hermes"])
        sup.harbor_containers = lambda: [
            "stale__env-main-1", "trial-a__env-main-1", "trial-b__env-main-1",
        ]

        check("a run in another process is visible", bool(sup.active_run(runs)), True)
        check("its trials are not called leftovers",
              supervisor.orphaned_containers(), ["stale__env-main-1"])

        # A hard kill never reaches the cleanup, so staleness cannot rely on it.
        dead = subprocess.Popen([sys.executable, "-c", "pass"])
        dead.wait()
        marker = sup.run_marker_path(runs)
        payload = json.loads(marker.read_text(encoding="utf-8"))
        payload["pid"] = dead.pid
        marker.write_text(json.dumps(payload), encoding="utf-8")

        check("a marker whose process is gone is ignored", sup.active_run(runs), None)
        check("  so the containers are leftovers again",
              sorted(supervisor.orphaned_containers()),
              ["stale__env-main-1", "trial-a__env-main-1", "trial-b__env-main-1"])

        sup.clear_run_marker(runs)
        check("clearing removes the marker", marker.exists(), False)
        check("  and clearing a missing one is not an error",
              sup.clear_run_marker(runs), None)

        # collect.load_runs iterates directories, so the marker must not look
        # like a run to it.
        check("the marker is a file, not a run directory",
              [p.name for p in runs.iterdir() if p.is_dir()], [])
    finally:
        sup.harbor_containers = original


def test_reaps_only_its_own_containers(tmp: Path) -> None:
    """Stopping must remove the containers this run started -- and no others.

    Docker owns containers, not the process we kill, so terminating the runner
    leaves task containers alive with their agents still calling the model. To
    the user that reads as a Stop button that did nothing. But a machine can be
    running unrelated containers, so ownership is decided by exclusion against
    what was already running when the job began.
    """
    import bench.supervisor as sup

    config = Config(endpoint=EndpointConfig(), runs_dir=str(tmp))
    supervisor = Supervisor(config)

    running = ["someone-elses__env-main-1", "mine-a__env-main-1", "mine-b__env-main-1"]
    removed: list[str] = []

    original_list, original_reap = sup.harbor_containers, sup.reap_containers
    sup.harbor_containers = lambda: list(running)
    sup.reap_containers = lambda names: (
        removed.extend(names) or {"removed": list(names), "failed": []}
    )
    # The grace loop polls once a second; nothing here needs it to elapse.
    original_grace, sup.CONTAINER_GRACE_S = sup.CONTAINER_GRACE_S, 0.0
    try:
        job = type("J", (), {"_precontainers": {"someone-elses__env-main-1"}})()
        result = supervisor._reap_run_containers(job)
        check("removed both of this run's containers", sorted(result),
              ["mine-a__env-main-1", "mine-b__env-main-1"])
        check("left the unrelated container alone",
              "someone-elses__env-main-1" in removed, False)

        # Harbor cleaned up after itself: nothing left to force-remove.
        removed.clear()
        running[:] = ["someone-elses__env-main-1"]
        check("no-op when the run left nothing behind",
              supervisor._reap_run_containers(job), [])
        check("  and nothing was force-removed", removed, [])
    finally:
        sup.harbor_containers, sup.reap_containers = original_list, original_reap
        sup.CONTAINER_GRACE_S = original_grace


def test_terminate_tree() -> None:
    """Stopping must reach the whole process group, not just the child we spawned."""
    proc = subprocess.Popen(
        [sys.executable, "-c", "import time\nwhile True: time.sleep(0.2)"],
        **_process_group_kwargs(),
    )
    time.sleep(0.5)
    check("child is running", proc.poll() is None, True)
    _terminate_tree(proc)
    try:
        proc.wait(timeout=15)
    except subprocess.TimeoutExpired:
        _kill_tree(proc)
        proc.wait(timeout=15)
    check("child is stopped", proc.poll() is not None, True)


def test_network_reaping() -> None:
    """Task networks litter like containers, and cost more when they do.

    A compose project creates a network as well as containers; killing the run
    removes neither. A network costs no CPU, memory or disk, so nothing looks
    wrong -- but each one holds a subnet out of a default pool of 32. Once they
    are gone every task in the next run dies at network creation with a compose
    error that never says "subnet", which reads as the benchmark being broken.
    """
    import bench.supervisor as sup

    networks = {
        # ours, idle -> reclaimable
        "adaptive-rejection-sampler__abc__env_default": 0,
        "write-compressor__def__env_default": 0,
        # ours, but a container is still attached -> must be left alone
        "in-flight-task__ghi__env_default": 1,
        # somebody else's work -> never ours to remove
        "my-other-project_default": 0,
        "bridge": 0,
    }
    removed: list[str] = []
    real_run = subprocess.run

    def fake_run(argv, **kwargs):
        class R:
            returncode = 0
            stdout = ""
        if argv[:3] == ["docker", "network", "ls"]:
            R.stdout = (
                "\n".join("bridge" for _ in networks)
                if "{{.Driver}}" in argv[-1]
                else "\n".join(networks)
            )
            return R
        if argv[:3] == ["docker", "network", "inspect"]:
            R.stdout = str(networks.get(argv[3], 0))
            return R
        if argv[:3] == ["docker", "network", "rm"]:
            removed.append(argv[3])
            return R
        return real_run(argv, **kwargs)

    sup.subprocess.run = fake_run
    try:
        idle = sorted(sup.orphaned_networks())
        check("only our task networks are reclaimable",
              idle, ["adaptive-rejection-sampler__abc__env_default",
                     "write-compressor__def__env_default"])
        check("a network with a container attached is left alone",
              "in-flight-task__ghi__env_default" in idle, False)
        check("another project's network is never touched",
              "my-other-project_default" in idle, False)

        sup.reap_networks(idle)
        check("reaping removes exactly those", sorted(removed), idle)

        pressure = sup.network_pool_pressure()
        check("pool pressure counts bridge networks",
              pressure["n_bridge_networks"], len(networks))
        check("...and says so before the pool runs dry",
              pressure["tight"], False)
    finally:
        sup.subprocess.run = real_run


def test_endpoint_watchdog(root: Path) -> None:
    """Ground truth for "was the endpoint up?", which nothing else records.

    A harness reports that its request failed, never why, and the container is
    gone before anyone looks. Without an independent sample, "the endpoint
    dropped" is an assumption -- and it is the assumption that hides a bug in
    our own code, so it must not be the default answer.
    """
    import http.server
    import threading as th

    from bench.watchdog import (
        HEALTH_FILENAME,
        EndpointWatchdog,
        _probe_once,
        health_around,
        health_url,
    )

    check("health url adds /v1 when absent",
          health_url("http://x.invalid:8000"), "http://x.invalid:8000/v1/models")
    check("...and does not double it",
          health_url("http://x.invalid:8000/v1/"), "http://x.invalid:8000/v1/models")

    class Quiet(http.server.BaseHTTPRequestHandler):
        def do_GET(self):
            body = b'{"data":[]}'
            self.send_response(200)
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def log_message(self, *a):
            pass

    server = http.server.HTTPServer(("127.0.0.1", 0), Quiet)
    port = server.server_address[1]
    th.Thread(target=server.serve_forever, daemon=True).start()
    url = f"http://127.0.0.1:{port}/v1/models"

    up = _probe_once(url)
    check("a reachable endpoint samples ok", (up["ok"], up["status"]), (True, 200))

    out = root / "wd" / HEALTH_FILENAME
    dog = EndpointWatchdog(url, out, interval_s=1.0)
    dog.start()
    time.sleep(1.4)
    dog.stop()
    check("samples are written while a run is in flight", out.exists(), True)
    n_up = len([ln for ln in out.read_text(encoding="utf-8").splitlines() if ln.strip()])
    check("...more than one of them", n_up >= 2, True)

    server.shutdown()
    server.server_close()
    down = _probe_once(url)
    check("an unreachable endpoint is recorded as such", down["ok"], False)
    check("...with the reason kept", bool(down.get("error")), True)

    # The correlation the whole thing exists for.
    sample_time = json.loads(out.read_text(encoding="utf-8").splitlines()[0])["at"]
    near = health_around(out.parent, sample_time, window_s=60.0)
    check("a trial's failure can be correlated with endpoint state",
          near.get("n_unreachable"), 0)
    check("no samples means no claim either way",
          health_around(root / "nothing-here", sample_time), {})


if __name__ == "__main__":
    test_network_reaping()
    with tempfile.TemporaryDirectory() as raw:
        root = Path(raw)
        test_guards(root)
        test_delete_guards(root)
        test_stop_marks_manifests(root)
        test_a_running_benchmarks_containers_are_not_orphans(root)
        test_a_cli_run_is_recognised_across_processes(root)
        test_reaps_only_its_own_containers(root)
        test_child_env_pins_config(root)
        test_endpoint_watchdog(root)
        test_terminate_tree()
    print("\n" + ("FAILED: " + ", ".join(failures) if failures else "all checks passed"))
    raise SystemExit(1 if failures else 0)
