"""Harbor agent adapter for Sentdex's minion.

minion is a single-file Python agent built for self-hosted models, and it is the
easiest of the four to drive: it ships a headless mode written for exactly this
purpose. From its source::

    # `--prompt-file <path>` (or `-f <path>`) reads the full task instruction
    # from a file, runs exactly one model turn, and exits -- no REPL, no banner,
    # no session save. Designed for headless benchmark harnesses
    # (Harbor/Terminal-Bench)

Three details decide how this adapter is written, and all three come from the
source rather than the README:

* **Configuration is per-source, not a single base URL.** The README summarises
  it as ``MINION_BASE_URL``, but one-shot mode fails with "no source configured
  -- set MINION_SOURCE_* env vars or use --source". The real shape is a named
  source: ``MINION_SOURCES=local`` plus ``MINION_SOURCE_LOCAL_BASE_URL``,
  ``_API_KEY`` and ``_MODEL``. Leaving the model blank makes minion ask the
  server what it is serving, but the benchmark names it explicitly so a run
  cannot be labelled with one model and generated by another.

* **One-shot saves no session**, so the usual token-accounting route -- the
  session JSON under ``MINION_SESSIONS_DIR`` -- does not exist here. What does
  exist is minion's append-only traffic log, "a record of every byte we ship to
  / receive from the server", written beside the script. That is copied out at
  the end of the run and parsed for usage.

* **Approvals must be off.** ``--yolo`` sets "never prompt"; without it the
  agent waits at the first approval for someone who is not there, and the trial
  burns its whole budget before failing.

The instruction goes through a file rather than argv, which is what ``-f`` is
for and which sidesteps shell quoting of a task description entirely.
"""

from __future__ import annotations

import json
import shlex
from typing import Any, override

from harbor.agents.installed.base import BaseInstalledAgent, CliFlag, with_prompt_template
from harbor.environments.base import BaseEnvironment
from harbor.models.agent.context import AgentContext

_REPO = "https://github.com/Sentdex/minion"
_INSTALL_DIR = "/opt/minion"
_SCRIPT = f"{_INSTALL_DIR}/minion.py"

#: minion writes its traffic log next to the script:
#:   LOG_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)),
#:                           "logs", "llamacpp.log")
#: Installing to a fixed directory is what makes that path predictable.
_TRAFFIC_LOG = f"{_INSTALL_DIR}/logs/llamacpp.log"

#: Package-manager and clone output, kept for when the install fails. Written
#: under /logs/agent because that directory is collected as a trial artifact --
#: an install that dies takes its container with it, so anything left elsewhere
#: is gone by the time anyone looks. Falls back to /tmp if it is not writable
#: yet, which still beats discarding it.
_INSTALL_LOG = "/logs/agent/minion-install.log"

_PROMPT_FILE = "/tmp/minion-task.txt"

#: The source name registered for our endpoint. Everything downstream derives
#: from it, including the env var spelling (MINION_SOURCE_<UPPER>_BASE_URL).
_SOURCE = "local"


class Minion(BaseInstalledAgent):
    """minion against an arbitrary OpenAI-compatible endpoint."""

    _OUTPUT_FILENAME = "minion.txt"
    _TRAFFIC_FILENAME = "minion-traffic.jsonl"

    CLI_FLAGS = [
        CliFlag("approval", cli="--approval", type="str"),
    ]

    def __init__(
        self,
        *args: Any,
        base_url: str | None = None,
        api_key: str = "sk-noop",
        # minion probes the context window itself -- against a llama.cpp server
        # it reads /v1/models and /props, the same source the runner probes, so
        # there is nothing to pass and no second setting that could disagree.
        # Only the output cap is configurable, and minion's default (16000)
        # differs from what the other harnesses are handed.
        max_tokens: int | str | None = None,
        **kwargs: Any,
    ) -> None:
        super().__init__(*args, **kwargs)
        self._base_url = base_url or self._get_env("MINION_SOURCE_LOCAL_BASE_URL")
        # minion's own default for a local server, which ignores the value.
        self._api_key = api_key or "sk-noop"
        self._max_tokens = int(max_tokens or 0) or None

    # ------------------------------------------------------------------
    # Identity
    # ------------------------------------------------------------------

    @staticmethod
    @override
    def name() -> str:
        return "minion"

    @override
    def get_version_command(self) -> str | None:
        # minion has no --version; the checked-out commit is the version that
        # matters for reproducing a run.
        return f"git -C {_INSTALL_DIR} rev-parse --short HEAD"

    @override
    def parse_version(self, stdout: str) -> str:
        lines = [line.strip() for line in stdout.strip().splitlines() if line.strip()]
        return lines[-1] if lines else stdout.strip()

    # ------------------------------------------------------------------
    # Install
    # ------------------------------------------------------------------

    @override
    async def install(self, environment: BaseEnvironment) -> None:
        await self.exec_as_root(
            environment,
            command=(
                "set -u; "
                f'log={_INSTALL_LOG}; mkdir -p /logs/agent 2>/dev/null || true; '
                ': >"$log" 2>/dev/null || log=/tmp/minion-install.log; '
                ': >"$log" 2>/dev/null || true; '
                "pkgs='git curl ca-certificates python3 python3-pip'; "
                "if command -v apt-get >/dev/null 2>&1; then "
                '  apt-get update >>"$log" 2>&1 || true; '
                '  apt-get install -y $pkgs >>"$log" 2>&1 || '
                '    apt-get install -y git python3 python3-pip >>"$log" 2>&1 || true; '
                "elif command -v apk >/dev/null 2>&1; then "
                '  apk add --no-cache git curl ca-certificates python3 py3-pip >>"$log" 2>&1 || true; '
                "elif command -v dnf >/dev/null 2>&1; then "
                '  dnf install -y git curl python3 python3-pip >>"$log" 2>&1 || true; '
                "elif command -v yum >/dev/null 2>&1; then "
                '  yum install -y git curl python3 python3-pip >>"$log" 2>&1 || true; '
                "fi; "
                # Check what this step exists to provide, not something the image
                # already had. Gating on python3 -- which every task image ships
                # -- meant a failed apt reported success, and the *next* step
                # died with git or pip missing and no output to say which.
                'missing=""; '
                'command -v git >/dev/null 2>&1 || missing="$missing git"; '
                'command -v python3 >/dev/null 2>&1 || missing="$missing python3"; '
                # pip is only needed to obtain openai; an image that already has
                # the module does not need it, and must not be failed for that.
                "python3 -c 'import openai' >/dev/null 2>&1 || "
                'python3 -m pip --version >/dev/null 2>&1 || missing="$missing pip"; '
                'if [ -n "$missing" ]; then '
                '  echo "minion install: still missing after package install:$missing"; '
                "  echo '--- package manager output (tail) ---'; "
                '  tail -n 40 "$log" 2>/dev/null || true; '
                "  exit 1; "
                "fi"
            ),
            env={"DEBIAN_FRONTEND": "noninteractive"},
        )

        ref = f" --branch {shlex.quote(self._version)}" if self._version else ""
        await self.exec_as_root(
            environment,
            command=(
                # Explicit checks rather than `set -e`, so a failure says which
                # step failed instead of only that the line exited non-zero.
                "set -u; "
                f'log={_INSTALL_LOG}; [ -w "$log" ] || log=/tmp/minion-install.log; '
                f"rm -rf {_INSTALL_DIR}; "
                f'if ! git clone --depth 1{ref} {_REPO} {_INSTALL_DIR} >>"$log" 2>&1; then '
                "  echo 'minion install: git clone failed'; "
                '  tail -n 30 "$log" 2>/dev/null || true; exit 1; '
                "fi; "
                # openai is minion's only dependency. Debian-derived images ship
                # an externally-managed Python that refuses a bare pip install,
                # so the flag is offered and ignored where it is not understood.
                'python3 -m pip install --quiet openai >>"$log" 2>&1 || '
                'python3 -m pip install --quiet --break-system-packages openai >>"$log" 2>&1 || '
                # Third fallback for images carrying an apt-installed copy of one
                # of openai's dependencies. pip resolves a newer version, tries to
                # uninstall the dpkg-owned one, and cannot -- packages installed by
                # dpkg have no RECORD file:
                #
                #   Cannot uninstall typing_extensions 4.13.2
                #   The package's contents are unknown: no RECORD file was found
                #
                # --ignore-installed leaves the system copy in place and installs
                # alongside it. Last rather than first because shadowing a distro
                # package is worth avoiding when the plain path works.
                'python3 -m pip install --quiet --break-system-packages '
                '--ignore-installed openai >>"$log" 2>&1 || true; '
                "if ! python3 -c 'import openai' >/dev/null 2>&1; then "
                "  echo 'minion install: openai is not importable after pip install'; "
                '  tail -n 30 "$log" 2>/dev/null || true; exit 1; '
                "fi; "
                f"test -f {_SCRIPT} || "
                f"{{ echo 'minion install: {_SCRIPT} missing after clone'; exit 1; }}"
            ),
        )

    # ------------------------------------------------------------------
    # Configuration
    # ------------------------------------------------------------------

    def _model_id(self) -> str:
        """The bare model id, without the ``local/`` provider prefix."""
        if not self.model_name:
            raise ValueError(
                "minion requires --model. Use '<provider>/<model-id>', e.g. "
                "'local/my-model'."
            )
        return (
            self.model_name.split("/", 1)[1]
            if "/" in self.model_name
            else self.model_name
        )

    def _agent_env(self) -> dict[str, str]:
        """The named-source configuration minion actually reads.

        A single MINION_BASE_URL does nothing: one-shot mode exits with "no
        source configured -- set MINION_SOURCE_* env vars or use --source".
        """
        prefix = f"MINION_SOURCE_{_SOURCE.upper()}"
        return {
            "MINION_SOURCES": _SOURCE,
            "MINION_ACTIVE": _SOURCE,
            f"{prefix}_BASE_URL": self._base_url or "",
            f"{prefix}_API_KEY": self._api_key,
            # Named rather than auto-resolved: a run whose model is discovered
            # could be labelled with one model and generated by another, which
            # is the one failure nothing downstream would reveal.
            f"{prefix}_MODEL": self._model_id(),
            # Never prompt. Belt to --yolo's braces.
            "MINION_APPROVAL": "yolo",
            # Keep any stray session state inside the container.
            "MINION_HOME": "/tmp/minion-home",
            **({"MINION_MAX_TOKENS": str(self._max_tokens)}
               if self._max_tokens else {}),
        }

    def _run_command(self) -> str:
        parts = [
            "python3",
            _SCRIPT,
            # "never prompt" -- overrides every other approval setting.
            "--yolo",
            # The instruction arrives as a file, which is what -f exists for and
            # which keeps a task description out of shell quoting entirely.
            "--prompt-file",
            _PROMPT_FILE,
        ]
        approval = self._resolved_flags.get("approval")
        if approval:
            parts += ["--approval", shlex.quote(str(approval))]
        return " ".join(parts)

    # ------------------------------------------------------------------
    # Run
    # ------------------------------------------------------------------

    @override
    @with_prompt_template
    async def run(
        self,
        instruction: str,
        environment: BaseEnvironment,
        context: AgentContext,
    ) -> None:
        if not self._base_url:
            raise ValueError(
                "minion needs an endpoint. Pass --ak base_url=http://host:port/v1"
            )

        env = self._agent_env()
        env["HARBOR_INSTRUCTION"] = instruction

        await self.exec_as_agent(
            environment,
            command=(
                f"mkdir -p /tmp/minion-home && "
                f'printf "%s" "$HARBOR_INSTRUCTION" > {_PROMPT_FILE}'
            ),
            env=env,
            timeout_sec=30,
        )

        run_cmd = (
            f"{self._run_command()} "
            f"2>&1 | stdbuf -oL tee /logs/agent/{self._OUTPUT_FILENAME}"
        )
        try:
            await self.exec_as_agent(environment, command=run_cmd, env=env)
        finally:
            # One-shot saves no session, so the traffic log is the only record
            # of usage. Copy it out even on failure -- a crashed run's traffic
            # is exactly the one worth reading.
            try:
                await self.exec_as_agent(
                    environment,
                    command=(
                        f"cp {_TRAFFIC_LOG} /logs/agent/{self._TRAFFIC_FILENAME} "
                        f"2>/dev/null || true"
                    ),
                    env=env,
                    timeout_sec=60,
                )
            except Exception:
                pass

    # ------------------------------------------------------------------
    # Token accounting
    # ------------------------------------------------------------------

    @staticmethod
    def _usage_of(node: Any) -> dict[str, Any] | None:
        """Find a provider usage object anywhere in a logged payload."""
        if isinstance(node, dict):
            usage = node.get("usage")
            if isinstance(usage, dict) and (
                "prompt_tokens" in usage or "completion_tokens" in usage
            ):
                return usage
            for value in node.values():
                found = Minion._usage_of(value)
                if found:
                    return found
        elif isinstance(node, list):
            for value in node:
                found = Minion._usage_of(value)
                if found:
                    return found
        return None

    def _traffic_totals(self) -> dict[str, int] | None:
        """Sum provider usage across every API call in the traffic log.

        Streaming responses report usage once per call, so summing the usage
        objects gives the totals for the trial. Raw provider fields are used
        rather than minion's normalized ones, because minion subtracts cached
        tokens out of its input count while Harbor's n_input_tokens is the
        total *including* cache -- mixing the two would quietly understate
        input on any endpoint with prompt caching.
        """
        path = self.logs_dir / self._TRAFFIC_FILENAME
        if not path.exists():
            return None

        totals = {"input": 0, "output": 0, "cache_read": 0}
        found = False
        for line in path.read_text(errors="replace").splitlines():
            line = line.strip()
            if not line.startswith("{"):
                continue
            try:
                record = json.loads(line)
            except json.JSONDecodeError:
                # A line truncated by a killed trial; the rest still counts.
                continue
            if record.get("dir") != "resp":
                continue
            usage = self._usage_of(record.get("data"))
            if not usage:
                continue
            prompt = usage.get("prompt_tokens")
            completion = usage.get("completion_tokens")
            if isinstance(prompt, (int, float)):
                totals["input"] += int(prompt)
                found = True
            if isinstance(completion, (int, float)):
                totals["output"] += int(completion)
                found = True
            details = usage.get("prompt_tokens_details")
            if isinstance(details, dict):
                cached = details.get("cached_tokens")
                if isinstance(cached, (int, float)):
                    totals["cache_read"] += int(cached)
        return totals if found else None

    @override
    def populate_context_post_run(self, context: AgentContext) -> None:
        totals = self._traffic_totals()
        if not totals:
            return
        context.n_input_tokens = totals["input"]
        context.n_output_tokens = totals["output"]
        context.n_cache_tokens = totals["cache_read"]
